# Generated by Django 3.0.3 on 2020-05-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200519_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peticion',
            old_name='id_Servicio',
            new_name='servicio',
        ),
    ]
